//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to settings.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Overrides.
        /// </summary>
        public static string HeaderCheckOverrides {
            get {
                return ResourceManager.GetString("HeaderCheckOverrides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample addin.
        /// </summary>
        public static string RibbonButtonName {
            get {
                return ResourceManager.GetString("RibbonButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select element.
        /// </summary>
        public static string SelectElement {
            get {
                return ResourceManager.GetString("SelectElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select new element.
        /// </summary>
        public static string SelectNewElement {
            get {
                return ResourceManager.GetString("SelectNewElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Solid fill&gt;.
        /// </summary>
        public static string SolidFillName {
            get {
                return ResourceManager.GetString("SolidFillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final element properties:.
        /// </summary>
        public static string TextFinalProperties {
            get {
                return ResourceManager.GetString("TextFinalProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FillPattern color.
        /// </summary>
        public static string TextForegroundFillColor {
            get {
                return ResourceManager.GetString("TextForegroundFillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FillPattern name.
        /// </summary>
        public static string TextForegroundFillPattern {
            get {
                return ResourceManager.GetString("TextForegroundFillPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FillPattern visibility.
        /// </summary>
        public static string TextForegroundFillVisible {
            get {
                return ResourceManager.GetString("TextForegroundFillVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is halftone.
        /// </summary>
        public static string TextIsHalftone {
            get {
                return ResourceManager.GetString("TextIsHalftone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line pattern color.
        /// </summary>
        public static string TextLinePatternColor {
            get {
                return ResourceManager.GetString("TextLinePatternColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line pattern name.
        /// </summary>
        public static string TextLinePatternName {
            get {
                return ResourceManager.GetString("TextLinePatternName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line pattern thickness.
        /// </summary>
        public static string TextLinePatternThickness {
            get {
                return ResourceManager.GetString("TextLinePatternThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check override properties to detect:.
        /// </summary>
        public static string TextOverrideProperties {
            get {
                return ResourceManager.GetString("TextOverrideProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency.
        /// </summary>
        public static string TextTransparency {
            get {
                return ResourceManager.GetString("TextTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample addin.
        /// </summary>
        public static string Title_SampleAddin {
            get {
                return ResourceManager.GetString("Title_SampleAddin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
